[package]
name = "pumpkin-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = [
    "item",
    "packet",
    "jukebox_song",
    "translation",
    "registry",
    "screen",
    "particle",
    "statistic",
    "sound",
    "recipes",
    "data_component",
    "attributes",
    "tracked_data",
    "meta_data_type",
    "chunk",
    "game_event",
    "game_rules",
    "entity",
    "dimension",
    "environment_attribute",
    "enchantment",
    "world",
    "scoreboard",
    "damage",
    "fluid",
    "block",
    "tag",
    "noise_router",
    "composter",
    "flower_pot",
    "effect",
    "structures",
    "potion",
    "material_rule",
    "noise_settings",
    "advancement",
    "carver",
    "villager",
    "placed_feature",
    "configured_feature",
    "slot_ranges",
    "bedrock_creative",
    "bedrock_biome",
    "map_color",
    "map_decoration",
    "dye_color",
    "block_transformer",
    "trial_spawner",
    "test_instance",
    "painting_variant",
    "context_provider",
    "instrument",
    "wolf_variant",
    "cat_variant",
    "frog_variant",
    "trim_material",
    "trim_pattern",
    "banner_pattern",
    "decorated_pot_pattern",
    "chat_type",
    "enchantment_provider",
    "cow_variant",
    "cow_sound_variant",
    "pig_variant",
    "pig_sound_variant",
    "chicken_variant",
    "chicken_sound_variant",
    "cat_sound_variant",
    "wolf_sound_variant",
    "zombie_nautilus_variant",
]

cow_variant = ["tag"]
cow_sound_variant = ["sound"]
pig_variant = ["tag"]
pig_sound_variant = ["sound"]
chicken_variant = ["tag"]
chicken_sound_variant = ["sound"]
cat_sound_variant = ["sound"]
wolf_sound_variant = ["sound"]
zombie_nautilus_variant = ["tag"]
enchantment_provider = ["enchantment", "item", "tag"]
instrument = ["sound"]
wolf_variant = []
cat_variant = []
frog_variant = []
trim_material = []
trim_pattern = []
banner_pattern = []
decorated_pot_pattern = []
chat_type = []
context_provider = []
painting_variant = []
test_instance = []
trial_spawner = []
block_transformer = ["block", "sound", "world", "tag"]
map_color = []
map_decoration = []
dye_color = []
advancement = []
bedrock_creative = []
bedrock_biome = []
item = []
packet = []
jukebox_song = []
translation = []
registry = []
screen = []
particle = []
statistic = []
sound = []
recipes = []
data_component = []
attributes = []
tracked_data = []
meta_data_type = []
chunk = ["noise_parameter", "biome", "chunk_status"]
game_event = []
game_rules = []
entity = ["entity_pose", "entity_status", "entity_type", "spawn_egg"]
dimension = []
environment_attribute = []
enchantment = []
world = ["world_event", "message_type"]
scoreboard = []
damage = []
fluid = []
tag = []
noise_router = []
composter = []
flower_pot = []
effect = []
structures = []
potion = ["potion_brewing"]
material_rule = []
noise_settings = []
chunk_gen_settings = ["noise_settings", "material_rule"]
carver = []
villager = ["item", "sound"]
slot_ranges = []

noise_parameter = []
biome = ["carver"]
chunk_status = []
entity_pose = []
entity_status = []
entity_type = ["sound"]
spawn_egg = []
world_event = []
message_type = []
placed_feature = []
configured_feature = []
block = []
potion_brewing = []

[dependencies]
phf = { workspace = true, features = ["macros"] }
pumpkin-util.workspace = true
pumpkin-nbt.workspace = true
serde = {workspace = true, features = ["rc"]}
crc-fast.workspace = true
rand.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "has_random_ticks"
harness = false

[package.metadata.cargo-machete]
ignored = ["phf"]

[lints]
workspace = true
