use heck::ToPascalCase;
use std::collections::BTreeMap;
use std::fs;

pub fn build() -> String {
    let json: BTreeMap<String, serde_json::Value> =
        serde_json::from_str(&fs::read_to_string("../../assets/items.json").unwrap())
            .expect("Failed to parse items.json");

    let mut code = String::new();
    code.push_str("// Generated by pumpkin-codegen. Do not edit.\n");
    code.push_str("#![allow(missing_docs, clippy::all)]\n\n");
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    code.push_str("pub enum Item {\n");

    for name in json.keys() {
        let pascal = name.to_pascal_case();
        code.push_str(&format!("    {pascal},\n"));
    }

    code.push_str("}\n\n");

    code.push_str("impl Item {\n");
    code.push_str(
        "    /// Returns the plain item name (e.g. `\"diamond\"` or `\"netherite_sword\"`).\n",
    );
    code.push_str("    #[must_use]\n");
    code.push_str("    pub const fn as_str(&self) -> &'static str {\n");
    code.push_str("        match self {\n");
    for name in json.keys() {
        let pascal = name.to_pascal_case();
        code.push_str(&format!("            Self::{pascal} => \"{name}\",\n"));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str(
        "    /// Returns the namespaced resource location (e.g. `\"minecraft:diamond\"`).\n",
    );
    code.push_str("    #[must_use]\n");
    code.push_str("    pub const fn resource_location(&self) -> &'static str {\n");
    code.push_str("        match self {\n");
    for name in json.keys() {
        let pascal = name.to_pascal_case();
        code.push_str(&format!(
            "            Self::{pascal} => \"minecraft:{name}\",\n"
        ));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Resolves a typed `Item` from a name or namespaced identifier.\n");
    code.push_str("    #[must_use]\n");
    code.push_str("    pub fn from_name(name: &str) -> Option<Self> {\n");
    code.push_str("        let clean = name.strip_prefix(\"minecraft:\").unwrap_or(name);\n");
    code.push_str("        match clean {\n");
    for name in json.keys() {
        let pascal = name.to_pascal_case();
        code.push_str(&format!(
            "            \"{name}\" => Some(Self::{pascal}),\n"
        ));
    }
    code.push_str("            _ => None,\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Resolves a typed `Item` from a registry key.\n");
    code.push_str("    #[must_use]\n");
    code.push_str("    pub fn from_registry_key(key: &str) -> Option<Self> {\n");
    code.push_str("        Self::from_name(key)\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("impl std::fmt::Display for Item {\n");
    code.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    code.push_str("        write!(f, \"{}\", self.resource_location())\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("impl AsRef<str> for Item {\n");
    code.push_str("    fn as_ref(&self) -> &str {\n");
    code.push_str("        self.as_str()\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    code
}
