[files]
extend-exclude = ["assets/", "crates/pumpkin-data/src/generated"]

[default.extend-words]
handled = "handled"
received = "received"
ba = "ba"
fo = "fo"
undescore = "undescore"
replaceables = "replaceables"
