[package]
name = "pumpkin-gui-api"
version.workspace = true
description = "Public data contract between the Pumpkin server and GUI frontends."
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sysinfo = { workspace = true, features = ["system", "disk", "component"] }
serde = { workspace = true, features = ["derive"] }
postcard.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
