[package]
name = "pumpkin-gui-api"
version.workspace = true
description = "Public data contract between the Pumpkin server and GUI frontends."
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
arc-swap.workspace = true
sysinfo = { workspace = true, features = ["system", "disk", "component"] }

[lints]
workspace = true
