[package]
name = "pumpkin-gametest"
version.workspace = true
description = "Minecraft GameTest framework for Pumpkin."
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
pumpkin-data = { workspace = true, features = ["block"] }
pumpkin-macros.workspace = true
pumpkin-nbt.workspace = true
pumpkin-util.workspace = true
pumpkin-world.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
